### ISSUE TITLE
to many sql variables

### ISSUE THREAD

**Issue by MrDefacto** [nmarley/sentinel#17] opened 2017-01-22 01:23 UTC
```
Traceback (most recent call last):
   File "/sentinel/scripts/crontab.py", line 181, in <module>
     main()
   File "/sentinel/scripts/crontab.py", line 149, in main
     perform_dashd_object_sync(dashd)
   File "/sentinel/scripts/crontab.py", line 20, in perform_dashd_object_sync
     GovernanceObject.sync(dashd)
   File "/sentinel/scripts/../lib/models.py", line 75, in sync
     for purged in self.purged_network_objects(list(golist.keys())):
   File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3156, in __iter__
     return iter(self.execute())
   File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3149, in execute
     self._qr = ResultWrapper(model_class, self._execute(), query_meta)
   File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2833, in _execute
     return self.database.execute_sql(sql, params, self.require_commit)
   File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3690, in execute_sql
     self.commit()
   File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3514, in __exit__
     reraise(new_type, new_type(*exc_args), traceback)
   File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3683, in execute_sql
     cursor.execute(sql, params or ())
 peewee.OperationalError: too many SQL variables
```

sqllite. latest version of sentinel.

**Comment by nmarley** [comment] 2017-01-22 01:32
Thanks! Can you please provide more context? What is the output of `SENTINEL_DEBUG=1 venv/bin/python scripts/crontab.py`?

**Comment by MrDefacto** [comment] 2017-01-22 02:03
SENTINEL_DEBUG=1 is very very noisy. I can try to use it but it will be very hard...

**Comment by nmarley** [comment] 2017-01-22 02:04
I'm not sure how to debug without any more information than this... looks like it's breaking on the gobject import, but not sure on what specifically.

**Comment by MrDefacto** [comment] 2017-01-22 02:09
it shows up in log few times one after another... then disappear by itself... as for now cannot reproduce. when it shows up i try enable debug.

**Comment by taw00** [comment] 2017-01-22 15:09
This happened to me yesterday ... maybe every third run for some time.
Nothing in the logs out of the ordinary. BUT... I found out my masternode had wedged on a block. I am not sure if that is related, except.... that once I had the masternode un-wedge... I didn't see it again.

I hope that helps.

**Comment by MrDefacto** [comment] 2017-01-22 15:46
still shouldn't happen at all... sentinel checks if mn is fully synced. :-)

**Comment by taw00** [comment] 2017-01-22 17:47
Oh. No doubt. I am just trying to give a bit more information in case someone can figure out where the bug is coming from.

**Comment by nmarley** [comment] 2017-01-24 15:28
Added debug logging/exception handling in 13aa09011d5ffa75c8953d51db0ac8695653ea1a to help resolve issues/reproduce.

**Comment by nmarley** [comment] 2017-02-04 20:23
No further issues after dc2f66be273ce55a389c2914e9669396c8307bf4. Closing due to both inability to reproduce (likely fixed in referenced commit), and main repo moving to https://github.com/dashpay/sentinel

**Closed by nmarley** 2017-02-04 20:23 UTC
Labels: bug
